language: python
python:
    - "2.7"
install:
    - pip install coveralls
    - pip install unittest2
script:
    - python test_calculator.py
    - coverage run --source=home test_calculator.py
after_sucess: 
  - coveralls
