language: python
install:
    - pip install nose coverage
    - pip install coveralls
    - pip install unittest2
script: python test_calculator.py nosetests --with-coverage --cover-package pypiview

after_sucess:
   coveralls
